import type { Metadata } from "next";
import { Libre_Baskerville, Inconsolata } from "next/font/google";
import "./globals.css";

const libreBaskerville = Libre_Baskerville({ 
  variable: "--font-libre-baskerville",
  style: "italic",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  style: "normal",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inconsolata.variable} ${libreBaskerville.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
